require('dotenv').config();

export const TASK_UPDATE = 'TASK_UPDATE';
  
export const EVENT_ADDED = 'EVENT_ADDED';
export const EVENT_UPDATED = 'EVENT_UPDATED';

export const STUDENT_JOINED = 'STUDENT_JOINED';
export const STUDENT_EXITED = 'STUDENT_EXITED';

export const ROOM_ADDED = 'ROOM_ADDED';
export const ROOM_UPDATED = 'ROOM_UPDATED';
export const ROOM_REMOVED = 'ROOM_REMOVED';

export const EVENT_JOIN = 'EVENT_JOIN';
export const EVENT_EXIT = 'EVENT_EXIT';

/* EVENTS FOR LECTURE */
export const EVENT_DOUBT = 'EVENT_DOUBT';
export const EVENT_EXPLAIN = 'EVENT_EXPLAIN';
export const EVENT_REPEAT = 'EVENT_REPEAT';
export const EVENT_CLEAR = 'EVENT_CLEAR';
export const EVENT_CLEAR_REVERT = 'EVENT_CLEAR_REVERT';

/* EVENTS FOR LSI */
export const EVENT_SUBMIT_ANSWERS = 'EVENT_SUBMIT_ANSWERS';

/* EVENTTS FOR CROWDTEST */
export const EVENT_SUBMIT_QUESTION = 'EVENT_SUBMIT_QUESTION';
export const EVENT_EDIT_QUESTION = 'EVENT_EDIT_QUESTION';
export const EVENT_DISPATCH_QUESTIONS = 'EVENT_DISPATCH_QUESTIONS';
export const EVENT_QUESTION_BATCH = 'EVENT_QUESTION_BATCH';
export const EVENT_TEST_RESULT = 'EVENT_TEST_RESULT';
export const EVENT_END_TEST = 'EVENT_END_TEST';
export const EVENT_SUBMIT_ANSWER = 'EVENT_SUBMIT_ANSWER';

export const EVENT_RESOURCE_UPLOAD = 'EVENT_RESOURCE_UPLOAD';

export const UPLOADS_DIR = 'uploads';

export const MONGODB_SERVER_URL = process.env.SRV_URL;
export const SERVER_PORT = process.env.PORT;